version: '3.8'
services:
  likes-token-v2:
    build:
      context: ./LikesTokenV2
      dockerfile: Dockerfile
    # Configuration for LikesTokenV2
    ports:
      - "3000:3000"  
  tictactoe:
    build:
      context: ./XO/TicTacToe
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Maps host port 3001 to container port 3000
